### ISSUE TITLE
Image [image Id] not found

### ISSUE THREAD

**Issue by fanux** [cloudfoundry-incubator/bosh-openstack-cpi-release#43]
I deploy cloudfoundry on openstack(devstack),  It came out an error:
```bash
Started deploying
  Creating VM for instance 'bosh/0' from stemcell '63580cce-1770-4240-9db9-07cf4e2e2c08'... Failed (00:00:02)
Failed deploying (00:00:04)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Command 'deploy' failed:
  Deploying:
    Creating instance 'bosh/0':
      Creating VM:
        Creating vm with stemcell cid '63580cce-1770-4240-9db9-07cf4e2e2c08':
          CPI 'create_vm' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"Image `63580cce-1770-4240-9db9-07cf4e2e2c08' not found","ok_to_retry":false}
```

**Comment by loewenstein** [comment]
Could you please provide the full output? Best would be to include the debug log output as well (see https://bosh.io/docs/using-bosh-init.html#logging to configure bosh-init to provide debug output).

I cannot imagine stemcell upload to succeed and VM creation to fail with "stemcell not found" without somebody or something deleting the image from Glance in between.

Did you happen to unstack.sh and stack.sh or otherwise interact with devstack Glance during the execution?

**Comment by fanux** [comment]
the VM CID is persisted in deployment state file in the same folder as the deployment manifest. I delete the old state.json file and redploy the error got away.
