### ISSUE TITLE
Hypervisor_type option required in bosh_openstack_cpi

### ISSUE THREAD

**Issue by arpitvipulsharma** [cloudfoundry-incubator/bosh-openstack-cpi-release#73]
Dear Team,
I am using qemu as a hypervisor in Openstack. I am unable to launch stemcell because for stemcell hypervisor_type is kvm. I am getting not enough host available. While I am able to launch instance manually. Please do needful for this. If possible try to put this option in cpi.yml, So we can change it.
Thanks & Regards:
Arpit Sharma

**Comment by mauromorales** [comment]
Hi @arpitvipulsharma 

The `hypervisor_type` attribute is taken from the stemcell and simply passed to OpenStack by the CPI without any processing. One thing you could try is to repack the stemcell using the bosh-cli, keep the same name and os version and just modify the cloud properties so that `hypervisor_type` is set to `qemu` you can follow the documentation here: https://bosh.io/docs/repack-stemcell.html. An alternative if you are not using the bosh-cli v2 then you could simply extract the stemcell and modify the property and then re-package the stemcell.

A question from me to you would be, do you have more than one hypervisor on that machine? And also could you provide the OpenStack logs where you see the error, so that we can get a clearer picture of what is going on.

Thanks!

**Comment by arpitvipulsharma** [comment]
Hi mauromorales! Thanks for your response. Issue solved. I have done by repacking of stemcell. I followed link which you shared. 
I was using only one hypervisor with QEMU. In nova schedular logs, I was getting image filter errors. 
Thanks to all for your support.

**Comment by mauromorales** [comment]
@arpitvipulsharma thank you for reaching out and glad I was able to help!

Closing fixed
