### ISSUE TITLE
Updating instance consul_z1 fails while bosh deploy

### ISSUE THREAD

**Issue by fluppirt** [cloudfoundry-incubator/bosh-openstack-cpi-release#90]
I'm trying to install cloud foundry on openstack and ran into a problem. 

![consul](https://user-images.githubusercontent.com/32242981/30783866-84bb7e76-a14a-11e7-90e2-cde78c8fe017.png)

![unbenannt](https://user-images.githubusercontent.com/32242981/30783846-11bed0da-a14a-11e7-9097-c4ace7921a75.PNG)

I've increased the timers in the Update Block of the deployment manifest and recreated the vm serveral times without success. 
While checking the logs of the consul vm, i've noticed that the files  
/var/vcap/jobs/consul_agent/config/certs/agent.crt
/var/vcap/jobs/consul_agent/config/certs/agent.key
are empty. The other ones seem to be correct. Both key and certificate are included in the stub-file.

Here are the logs:

[consul_agent.stderr.log](https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/files/1327426/consul_agent.stderr.log)

[consul_agent.stdout.log](https://github.com/cloudfoundry-incubator/bosh-openstack-cpi-release/files/1327427/consul_agent.stdout.log)

has anyone an idea what seems to be the issue here?

**Comment by voelzmo** [comment]
Hi @fluppirt 

thanks for reporting this issue. It seems like this isn't actually OpenStack related, but rather an issue with how you deploy Cloud Foundry itself. Please re-open this issue on either https://github.com/cloudfoundry/cf-release or https://github.com/cloudfoundry/cf-deployment, depending on what you're using.

I'm closing this issue here for now.
